// Generated by Scapix Language Bridge
// https://www.scapix.com

//#include <pocket/services/countdown.hpp>

#import "Constants.h"
#import "CountDown.h"
#import "Device.h"
#import "Globals.h"
#import "Property.h"
#import "User.h"


@interface CountDown ()
//@property pocket::services::CountDown* countDown;
@end



@implementation CountDown
//@synthesize  countDown;

-(instancetype)initWithUser:( User* )user sessionTimeoutInSeconds:(int16_t)sessionTimeoutInSeconds;
{

    return self;
}

-(void)dealloc
{
//
//    if(countDown)
//    {
//        delete countDown;
//    }
}

-(void)setCallback:(void(^)(void))callback
{

}


-(void)start
{
//    countDown->start();
}

-(void)stop
{
//    countDown->stop();
}

-(void)updateTimeLeft
{
//    countDown->updateTimeLeft();
}

-(BOOL)isStarted
{
//	return countDown->isStarted();
    return false;
}

@end
