// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <pocket/services/countdown.hpp>
using std::nothrow;

#import "Constants.h"
#import "CountDown.h"
#import "Device.h"
#import "Globals.h"
#import "Property.h"
#import "User.h"


extern pocket::pods::Device::Ptr convert(const Device* device);
extern Device* convert(const pocket::pods::Device::Ptr &group);
extern pocket::pods::Property::Ptr convert(const Property* user);
extern Property* convert(const pocket::pods::Property::Ptr &property);
extern pocket::pods::User::Ptr convert(const User* user);
extern User* convert(const pocket::pods::User::Ptr &user);


@interface CountDown ()
@property pocket::services::CountDown* countDown;
@end



@implementation CountDown
@synthesize  countDown;

-(instancetype)initWithUser:( User* )user sessionTimeoutInSeconds:(int16_t)sessionTimeoutInSeconds;
{
    if(self = [super init])
    {
//        auto &&u = convert(user);
//        u->referenceSession = ONE_SESSION;
//        countDown = new(nothrow) pocket::services::CountDown(u, ONE_SESSION, sessionTimeoutInSeconds);
        countDown = new(nothrow) pocket::services::CountDown(convert(user), ONE_SESSION, sessionTimeoutInSeconds);
        if(countDown == nullptr)
        {
            return Nil;
        }
    }
    return self;
}

-(void)dealloc
{

    if(countDown)
    {
        delete countDown;
    }
}

-(void)setCallback:(void(^)(void))callback
{
    countDown->setCallback([callback](auto str)
    {
        callback();
    });
}


-(void)start
{
    countDown->start();
}

-(void)stop
{
    countDown->stop();
}

-(void)updateTimeLeft
{
    countDown->updateTimeLeft();
}

-(BOOL)isStarted
{
	return countDown->isStarted();
}

@end
