// Generated by Scapix Language Bridge
// https://www.scapix.com

//#include <pocket/pods/field.hpp>

#import "Field.h"

#include <memory>
using namespace std;


@interface Field ()
//@property uint32_t _id;
//@property uint32_t _serverId;
//@property uint32_t _groupId;
//@property uint32_t _groupFieldId;
//@property NSString* _title;
//@property NSString* _value;
//@property BOOL _isHidden;
//@property BOOL _synchronized;
//@property BOOL _deleted;
//@property uint32_t _referenceUserId;
//@property NSString* _referenceSession;
@end

@implementation Field

//@synthesize  _id;
//@synthesize _serverId;
//@synthesize _groupId;
//@synthesize _groupFieldId;
//@synthesize _title;
//@synthesize _value;
//@synthesize _isHidden;
//@synthesize _synchronized;
//@synthesize _deleted;
//@synthesize _referenceUserId;
//@synthesize _referenceSession;

-(instancetype)init
{
    if(self = [super init])
    {

    }
    return self;
}

-(instancetype)initWithId:(uint32_t)id serverId:(uint32_t)serverId groupId:(uint32_t)groupId groupFieldId:(uint32_t)groupFieldId title:(NSString*)title value:(NSString*)value isHidden:(BOOL)isHidden synchronized:(BOOL)synchronized deleted:(BOOL)deleted
{
    if(self = [super init])
    {
//        _id = id;
//        _serverId = serverId;
//        _groupId = groupId;
//        _groupFieldId = groupFieldId;
//        _title = title;
//        _value = value;
//        _isHidden = isHidden;
//        _synchronized = synchronized;
//        _deleted = deleted;
    }
    return self;
}

-(void)setid:(uint32_t)id
{
//    _id = id;
}

-(uint32_t)getid
{
//    return _id;
    return 0;
}

-(void)setServerId:(uint32_t)id
{
//    _serverId = id;
}

-(uint32_t)getServerId
{
//    return _serverId;
    return 0;
}

-(void)setGroupId:(uint32_t)groupId
{
//    _groupId = groupId;
}

-(uint32_t)getGroupId
{
//    return _groupId
    return 0;
}

-(void)setGroupFieldId:(uint32_t)groupFieldId
{
//    _groupFieldId = groupFieldId;
}

-(uint32_t)getGroupFieldId
{
//    return _groupFieldId;
    return 0;
}

-(void)setTitle:(NSString*)title
{
//    _title = title;
}

-(NSString*)getTitle
{
//    return _title;
return @"";
}

-(void)setValue:(NSString*)value
{
//    _value = value;
}

-(NSString*)getValue
{
//    return _value;
    return @"";
}

-(void)setIsHidden:(BOOL)isHidden
{
//    _isHidden = isHidden;
    
}

-(BOOL)getIsHidden
{
//	return _isHidden;
    return true;
}

-(void)setSynchronized:(BOOL)synchronized
{
//    _synchronized = synchronized;
}

-(BOOL)getSynchronized
{
//    return _synchronized;
    return true;
}

-(void)setDeleted:(BOOL)deleted
{
//    _deleted = deleted;
}

-(BOOL)getDeleted
{
//    return _deleted;
    return false;
}


-(void)setReferenceUserId:(uint32_t)referenceUserId
{
//    _referenceUserId = referenceUserId;
}

-(uint32_t)getReferenceUserId
{
//    return _referenceUserId;
    return 0;
}

-(void)setReferenceSession:(NSString*)referenceSession
{
//    _referenceSession = referenceSession;
}

-(NSString*)getReferenceSession
{
//    return _referenceSession;
    return @"";
}

@end

//pocket::pods::Field::Ptr convert(const Field* field)
//{
//    
//    auto &&ret =  make_shared<pocket::pods::Field>(
//        [field getid]
//        ,[field getServerId]
//        ,[field getGroupId]
//        ,[field getGroupFieldId]
//        ,[[field getTitle] UTF8String]
//        ,[[field getValue] UTF8String]
//        ,[field getIsHidden]
//        ,[field getSynchronized]
//        ,[field getDeleted]
//    );
//    
//    ret->referenceSession = [[field getReferenceSession] UTF8String];
//    ret->referenceUserId = [field getReferenceUserId];
//    return ret;
//}

//Field* convert(const pocket::pods::Field::Ptr &field)
//{
//    Field *ret = [[Field alloc] init];
//    
//    [ret setid:field->id];
//    [ret setServerId:field->serverId];
//    [ret setGroupId: field->groupId];
//    [ret setGroupFieldId: field->groupFieldId];
//    [ret setTitle: [NSString stringWithCString:field->title.c_str() encoding:NSUTF8StringEncoding] ];
//    [ret setValue: [NSString stringWithCString:field->value.c_str() encoding:NSUTF8StringEncoding] ];
//    [ret setIsHidden: field->isHidden];
//    [ret setSynchronized: field->synchronized];
//    [ret setDeleted: field->deleted];
//    [ret setReferenceUserId: field->referenceUserId];
//    [ret setReferenceSession: [NSString stringWithCString:field->referenceSession.c_str() encoding:NSUTF8StringEncoding]];
//    return ret;
//}
