// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <pocket/dao/userdao.hpp>
#include <pocket/globals.hpp>
using std::nothrow;

#import "Constants.h"
#import "Device.h"
#import "Globals.h"
#import "User.h"

extern pocket::pods::Device::Ptr convert(const Device* device);
extern Device* convert(const pocket::pods::Device::Ptr &group);
extern pocket::pods::User::Ptr convert(const User* user);
extern User* convert(const pocket::pods::User::Ptr &user);


namespace
{
    Globals* singleton = Nil;
}


@interface Globals ()
@property pocket::Globals* globals;
@end

@implementation Globals
@synthesize  globals;

-(instancetype)init
{
    if(self = [super init])
    {
        globals = pocket::Globals::getInstance().get();
    }
    return self;
}

+(Globals*)getInstance
{
    if(singleton == Nil)
    {
        singleton = [Globals new];
    }
    return singleton;
}

-(NSString*)getBasePath
{
    return [NSString stringWithCString:globals->getBasePath().c_str() encoding:NSUTF8StringEncoding];
}

-(void)setUser:(User*)user
{
    globals->setUser(ONE_SESSION, convert(user));
}

-(void)setUserLastUpdate:(uint32_t)user_id user:(User*)user
{
    globals->setUserLastUpdate(user_id, convert(user));
}


-(User* _Nullable )getUser
{
    return convert(globals->getUser(ONE_SESSION));
}

-(User*)getSafeUser
{
    return convert(globals->getSafeUser(ONE_SESSION));
}

-(Device*)getDevice
{
    return convert(globals->getDevice(ONE_SESSION));
}

-(void)setDevice:(Device*)device
{
    globals->setDevice(ONE_SESSION, convert(device));
}

-(NSString*)getVersion
{
    return [NSString stringWithCString:globals->getVersion().c_str() encoding:NSUTF8StringEncoding];
}

-(void)initSystemCrypto:(NSString*)serialNumber
{
    globals->initSystemCrypto(ONE_SESSION, [serialNumber UTF8String]);
}

-(void)initServerCrypto:(NSString*)key
{
    globals->initServerCrypto([key UTF8String]);
}

-(void)initUserCrypto:(NSString*)key
{
    globals->initUserCrypto(ONE_SESSION, [key UTF8String]);
}

-(void)initialize:(NSString*)serialNumber basePath:(NSString*)basePath urlFile:(BOOL)urlFile
{
    globals->initialize([basePath UTF8String], urlFile);
    
    auto &&users = pocket::dao::UserDao::getInstance()->getList();
    if (!users.empty())
    {
        users[0]->referenceSession = ONE_SESSION;
        
        globals->setUser(ONE_SESSION, users[0]);
    }
}

@end
