// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "Constants.h"
#import "Device.h"
#import "Globals.h"
#import "User.h"


namespace
{
    Globals* singleton = Nil;
}


@interface Globals ()
//@property pocket::Globals* globals;
@end

@implementation Globals
//@synthesize  globals;

-(instancetype)init
{
    if(self = [super init])
    {

    }
    return self;
}

+(Globals*)getInstance
{
    if(singleton == Nil)
    {

    }
    return singleton;
}

-(NSString*)getBasePath
{
    return @"";
}

-(void)setUser:(User*)user
{

}

-(void)setUserLastUpdate:(uint32_t)user_id user:(User*)user
{
    
}


-(User* _Nullable )getUser
{
    return nil;
}

-(User*)getSafeUser
{
    return [User new];
}

-(Device*)getDevice
{
    return nil;
}

-(void)setDevice:(Device*)device
{
}

-(NSString*)getVersion
{
    return @"";
}

-(void)initSystemCrypto:(NSString*)serialNumber
{
}

-(void)initServerCrypto:(NSString*)key
{
}

-(void)initUserCrypto:(NSString*)key
{
}

-(void)initialize:(NSString*)serialNumber basePath:(NSString*)basePath urlFile:(BOOL)urlFile
{

}

@end
