// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <pocket/controllers/logincontroller.hpp>
using namespace std;

#import "Device.h"
#import "Field.h"
#import "Globals.h"
#import "Group.h"
#import "Groupfield.h"
#import "LoginController.h"
#import "User.h"
#import "Constants.h"

extern pocket::pods::User::Ptr convert(const User* user);

@interface LoginController ()

@property pocket::controllers::LoginController *controller;

@end


@implementation LoginController
@synthesize controller;


-(instancetype)init
{
    if(self = [super init])
    {
        controller = new(nothrow) pocket::controllers::LoginController(ONE_SESSION);
        if(controller == nullptr)
        {
            return Nil;
        }
    }
    return self;
}


-(void)dealloc
{

    if(controller)
    {
        delete controller;
    }
}

-(void)loginBiometric:(void(^)(NSString*))callback
{
    controller->loginBiometric([callback](auto pwd)
    {
        callback([NSString stringWithCString:pwd.c_str() encoding:NSUTF8StringEncoding]);
    });
}

-(void)login:(NSString*)system deviceSerial:(NSString*)deviceSerial host:(NSString*)host hostAuthUser:(NSString*)hostAuthUser hostAuthPasswd:(NSString*)hostAuthPasswd email:(NSString*)email passwd:(NSString*)passwd callback:(void(^)(uint8_t))callback
{
    promise<pocket::controllers::LoginController::Status> p;
    auto &&t = controller->login([system UTF8String]
                      , [deviceSerial UTF8String]
                      , [host UTF8String]
                      , [hostAuthUser UTF8String]
                      , [hostAuthPasswd UTF8String]
                      , [email UTF8String]
                      , [passwd UTF8String]
                      , p);
    
    t.join();
    
    callback(static_cast<uint8_t>(p.get_future().get()));
}

-(uint8_t)insertUser:(User*)user
{
    auto &&cppUser = convert(user);
    promise<pocket::controllers::LoginController::Status> p;
    
    auto &&t = controller->insertUser(cppUser, p);
    
    return 0;
}

+(uint8_t)getStatus
{
    return static_cast<uint8_t>(pocket::controllers::LoginController::getStatus());
}

@end
