// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <pocket/stacknavigator.hpp>
using std::nothrow;

#import "Constants.h"
#import "Group.h"
#import "Pair.h"
#import "StackNavigator.h"

extern pocket::pods::Group::Ptr convert(const Group* group);
extern Group* convert(const pocket::pods::Group::Ptr &group);
extern pocket::pods::Pair::Ptr convert(const Pair* pair);
extern Pair* convert(const pocket::pods::Pair::Ptr &pair);

namespace
{
    StackNavigator* singleton = Nil;
}


@interface StackNavigator ()
@property pocket::StackNavigator* stackNavigator;
@end



@implementation StackNavigator
@synthesize  stackNavigator;

-(instancetype)init
{
    if(self = [super init])
    {
        stackNavigator = pocket::StackNavigator::getInstance().get();
    }
    return self;
}

-(void)push:(Group*)group search:(NSString*)search
{
    stackNavigator->push(ONE_SESSION, convert(group), [search UTF8String]);
}

-(Pair*)get
{
    return convert(stackNavigator->get(ONE_SESSION));
}

-(Pair*)pop
{
    return convert(stackNavigator->pop(ONE_SESSION));
}

-(int64_t)size
{
    return stackNavigator->size(ONE_SESSION);
}

-(void)clear
{
    stackNavigator->clear(ONE_SESSION);
}

+(StackNavigator*)getInstance
{
    if(singleton == Nil)
    {
        singleton = [StackNavigator new];
    }
    return singleton;
}

@end
